"""add allow_multiple_submissions to surveys

Revision ID: 2c1453a5fcad
Revises: c1c70a5bfe80
Create Date: 2026-01-15 16:06:50.642317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c1453a5fcad'
down_revision: Union[str, Sequence[str], None] = 'c1c70a5bfe80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_logs_account_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_integration_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_schema_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_constraint(op.f('uq_survey_invites_token_hash'), 'survey_invites', type_='unique')
    op.drop_index(op.f('ix_survey_invites_token_hash'), table_name='survey_invites')
    op.create_index(op.f('ix_survey_invites_token_hash'), 'survey_invites', ['token_hash'], unique=True)
    op.add_column('survey_responses', sa.Column('is_latest', sa.Boolean(), nullable=False))
    op.alter_column('survey_responses', 'submission_batch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('survey_responses', 'row_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_survey_responses_row_index'), table_name='survey_responses')
    op.create_unique_constraint('uq_submission_row', 'survey_responses', ['submission_batch_id', 'row_index'])
    op.add_column('surveys', sa.Column('allow_multiple_submissions', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('surveys', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'CLOSED', name='surveystatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('surveys', 'storage_type',
               existing_type=postgresql.ENUM('DATABASE', 'AZURE', 'SHAREPOINT', 'S3', 'AZURE_BLOB', name='storagetype'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('surveys', 'is_migrated',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'is_migrated',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('surveys', 'storage_type',
               existing_type=postgresql.ENUM('DATABASE', 'AZURE', 'SHAREPOINT', 'S3', 'AZURE_BLOB', name='storagetype'),
               server_default=sa.text("'DATABASE'::storagetype"),
               existing_nullable=False)
    op.alter_column('surveys', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'CLOSED', name='surveystatus'),
               server_default=sa.text("'ACTIVE'::surveystatus"),
               existing_nullable=False)
    op.drop_column('surveys', 'allow_multiple_submissions')
    op.drop_constraint('uq_submission_row', 'survey_responses', type_='unique')
    op.create_index(op.f('ix_survey_responses_row_index'), 'survey_responses', ['row_index'], unique=False)
    op.alter_column('survey_responses', 'row_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('survey_responses', 'submission_batch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('survey_responses', 'is_latest')
    op.drop_index(op.f('ix_survey_invites_token_hash'), table_name='survey_invites')
    op.create_index(op.f('ix_survey_invites_token_hash'), 'survey_invites', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_survey_invites_token_hash'), 'survey_invites', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('schema_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('integration_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rows_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rows_failed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('request_headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('integration_logs_pkey'))
    )
    op.create_index(op.f('ix_integration_logs_schema_id'), 'integration_logs', ['schema_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_integration_id'), 'integration_logs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_account_id'), 'integration_logs', ['account_id'], unique=False)
    # ### end Alembic commands ###
